name = "Pack Wiz Base Pack"
author = "ChloePrime"
version = "0.0.2-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d49f06603f632d60a1be9eecd9fea440070e72e338c60a638175dc89630cae61"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"
